resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/Kevin-Fries-Altoros/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    config:
      platform: linux

      inputs:
      - name: flight-school

      image_resource:
        type: docker-image
        source: 
          repository: ruby
          tag: 2.3.0

      run:
        path: ./flight-school/ci/test.sh

